#!/bin/bash

# integration test for mt_prepend_gtf.py script
# exits 0 if the output of the script is correct on a test file, 1 otherwise

test_dir=$(dirname $0)

if ! diff -q ${test_dir}/test_out.gtf \
    <(mt_prepend_gtf.py ${test_dir}/test_in.gtf)
then
    exit 1
else
    exit 0
fi
