#!/bin/bash

# integration test for mt_prepend_gtf.py script
# exits 0 if the output of the script is correct on a test file, 1 otherwise

if ! diff -q test_out.gtf <(python ../mt_prepend_gtf.py test_in.gtf)
then
    exit 1
else
    exit 0
fi
